### ISSUE TITLE
Add possibility to change maximum zoom scale for the ScalingImageView.

### ISSUE THREAD

**Issue by heikkihautala** [NYTimes/NYTPhotoViewer#48]

**Comment by cdzombak** [comment]
This could easily be achieved by:

-Making the maximum zoom scale a property on [`NYTScalingImageView`](https://github.com/NYTimes/NYTPhotoViewer/blob/2fd86f52b4712f93ddd0b78795a0c074afadd099/Pod/Classes/ios/NYTScalingImageView.h), setting it to `1.0` in the initializer, and using it instead of the hardcoded [`1.0`](https://github.com/NYTimes/NYTPhotoViewer/blob/2fd86f52b4712f93ddd0b78795a0c074afadd099/Pod/Classes/ios/NYTScalingImageView.m#L91)
- Either adding a `maximumPhotoZoomScale` property to [`NYTPhotosViewController`](https://github.com/NYTimes/NYTPhotoViewer/blob/2fd86f52b4712f93ddd0b78795a0c074afadd099/Pod/Classes/ios/NYTPhotosViewController.h) _or_ an optional `-photosViewController:maximumZoomScaleForPhoto:` method to [`NYTPhotosViewControllerDelegate`](https://github.com/NYTimes/NYTPhotoViewer/blob/2fd86f52b4712f93ddd0b78795a0c074afadd099/Pod/Classes/ios/NYTPhotosViewController.h#L112). I am not sure offhand which approach is preferable here.
- Finally, using that property or delegate method when creating a `NYTPhotoViewController` in [`newPhotoViewControllerForPhoto:`](https://github.com/NYTimes/NYTPhotoViewer/blob/2fd86f52b4712f93ddd0b78795a0c074afadd099/Pod/Classes/ios/NYTPhotosViewController.m#L373).

We would welcome a PR to this effect and any further discussion on the best way to expose this functionality on `NYTPhotosViewController`.

**Comment by heikkihautala** [comment]
I made a PR: https://github.com/NYTimes/NYTPhotoViewer/pull/51. I decided to go with the delegate approach, because it enables the user to set different maximum zoom scale for each photo if necessary.

**Comment by cdzombak** [comment]
@heikkihautala thanks! I'll take a look asap.

**Comment by cdzombak** [comment]
closed by #51

**Comment by schystz** [comment]
Hi. I don't get the `photosViewController:maximumZoomScaleForPhoto:` protocol when installing NYTPhotoViewer via Cocoapods. It installs the 0.1.2 version when specifying `pod 'NYTPhotoViewer'` in the Podfile.

**Comment by MichaelSelsky** [comment]
That's because version 0.1.2 was released before this pull request was merged. I'll work on getting a new release on Monday. Until then you can point the most recent changes in this pod by using this line in your Podfile:
```Ruby
pod 'NYTPhotoViewer', :head
```

**Comment by MichaelSelsky** [comment]
That's because version 0.1.2 was released before this feature was added. I'll work on getting a new release on Monday. Until then you can point the most recent changes in this pod by using this line in your Podfile:
```Ruby
pod 'NYTPhotoViewer', :head
```

**Comment by andrew8712** [comment]
Is this working? I have implemented `photosViewController:maximumZoomScaleForPhoto:`, but it never gets called.

**Comment by cdzombak** [comment]
yes, this was merged in https://github.com/NYTimes/NYTPhotoViewer/pull/51 a while ago and is included in recent releases.

is it possible you're hitting bug #95 which is fixed in https://github.com/NYTimes/NYTPhotoViewer/releases/tag/1.1.0 ?

**Comment by andrew8712** [comment]
No, I use the latest release (1.1.0).

Should I do anything besides implementing this delegate method to achieve max zoom functionality?

**Comment by cdzombak** [comment]
> Should I do anything besides implementing this delegate method to achieve max zoom functionality?

That should be all you need.

> No, I use the latest release (1.1.0).

are you using the new designated initializer? It takes a delegate and if you're using a delegate you should use this initializer: 

```
- (instancetype)initWithPhotos:(NSArray <id <NYTPhoto>> * _Nullable)photos initialPhoto:(id <NYTPhoto> _Nullable)initialPhoto delegate:(nullable id <NYTPhotosViewControllerDelegate>)delegate
```

**Comment by andrew8712** [comment]
Thanks, this worked. Curious, it didn't work this way:

    let photosViewController = NYTPhotosViewController(photos: images, initialPhoto: item)
    photosViewController.delegate = self

**Comment by cdzombak** [comment]
> Curious, it didn't work this way: …

You're running into https://github.com/NYTimes/NYTPhotoViewer/issues/95 .
