### ISSUE TITLE
'interfaceOrientation' is deprecated: first deprecated in iOS 8.0

### ISSUE THREAD

**Issue by hdoria** [NYTimes/NYTPhotoViewer#54]

**Comment by stevenxiaoyang** [comment]
[[UIApplication sharedApplication] statusBarOrientation] instead

**Comment by bcapps** [comment]
While that might be a generic solution, for this project that won't work because the interface orientation of the specific view controller is important. `interfaceOrientation` is only used in one place in the animator and only on iOS 7, so the right solution is to either use a #define so that the code doesn't get compiled pre-iOS 8, or simply suppress the warning with clang push/pop.

**Comment by danielgalasko** [comment]
@bcapps alternatively you could ignore the interface orientation and instead use the transform of the window. I actually answered a similar post a while back http://stackoverflow.com/a/24800369/1652402

Will see if I have time to build a PR

**Comment by bcapps** [comment]
It looks like all references to `interfaceOrientation` have been removed in develop with changing the minimum supported version to iOS 8. I think that this can be closed cc @cdzombak.

**Comment by cdzombak** [comment]
References to `interfaceOrientation` were removed in #84.
