### ISSUE TITLE
UINavigationBar appearance

### ISSUE THREAD

**Issue by ItsTipTop** [NYTimes/NYTPhotoViewer#55]
When application has custom UINavigationBar appearance NYTPhotoViewer do not ignore it.
![ios simulator screen shot 15 2015 1 33 19](https://cloud.githubusercontent.com/assets/1473763/7643482/9363742a-faa2-11e4-8b39-7ca10c151a87.png)

**Comment by cdzombak** [comment]
@ItsTipTop can you please clarify which properties of `UINavigationBar`'s appearance you changed to get that result? And can you confirm whether you changed them using `[UINavigationBar appearance]`?

My quick attempt to reproduce this problem was:

```objc
    [UINavigationBar appearance].tintColor = [UIColor orangeColor];
    [UINavigationBar appearance].backgroundColor = [UIColor whiteColor];
```

which resulted in:

![Uploading Screen Shot 2015-05-18 at 15.57.20.png…]()

so any additional information you can provide would be helpful.

**Comment by ItsTipTop** [comment]
Yes
Here it is:

    [UINavigationBar appearance].barTintColor = [UIColor mainBackgroundColor];
    [UINavigationBar appearance].tintColor = [UIColor mainColor];
    [UINavigationBar appearance].translucent = NO;
    [[UINavigationBar appearance] setTitleTextAttributes:@{
                                                           NSForegroundColorAttributeName: [UIColor mainColor],
                                                           NSFontAttributeName: [UIFont systemFontOfSize:16.f],
                                                           }];
    [UINavigationBar appearance].backIndicatorImage = alignedImage;
    [UINavigationBar appearance].backIndicatorTransitionMaskImage = alignedImage;


Here my fix:

    NYTPhotosViewController *photosViewController = [[NYTPhotosViewController alloc] initWithPhotos:self.photos initialPhoto:initialPhoto];
    
    photosViewController.overlayView.navigationBar.barTintColor = nil;
    photosViewController.overlayView.navigationBar.tintColor = nil;
    photosViewController.overlayView.navigationBar.translucent = YES;
    photosViewController.overlayView.navigationBar.backIndicatorImage = nil;
    photosViewController.overlayView.navigationBar.backIndicatorTransitionMaskImage = nil;
    [photosViewController.overlayView.navigationBar setTitleTextAttributes:nil];

After this everything works fine!

**Comment by cdzombak** [comment]
@ItsTipTop thanks for the info.

**Comment by sibljon** [comment]
I'm having similar issues tho those reported here. The navigation bar is taking on the appearance settings that I've defined within my app via the UIAppearance proxy methods. I'm using `NYTPhotoViewer` commit e80e8767f3780d2df37c6f72cbab15d6c7232911 (1.1.0).

Would folks consider merging a Pull Request that moves the `UINavigationBar` configuration to within `-`-[NYTPhotosOverlayView layoutSubviews]`? So, for example, `-layoutSubviews` becomes:

```obj-c
- (void)layoutSubviews {
    // The navigation bar has a different intrinsic content size upon rotation, so we must update to that new size.
    // Do it without animation to more closely match the behavior in `UINavigationController`
    [UIView performWithoutAnimation:^{
        [self.navigationBar invalidateIntrinsicContentSize];
        [self.navigationBar layoutIfNeeded];
    }];

    // Make navigation bar background fully transparent.
    self.navigationBar.backgroundColor = [UIColor clearColor];
    self.navigationBar.barTintColor = nil;
    self.navigationBar.translucent = YES;
    self.navigationBar.shadowImage = [[UIImage alloc] init];
    [self.navigationBar setBackgroundImage:[[UIImage alloc] init] forBarMetrics:UIBarMetricsDefault];
    
    [super layoutSubviews];

    if ([self.captionView conformsToProtocol:@protocol(NYTPhotoCaptionViewLayoutWidthHinting)]) {
        [(id<NYTPhotoCaptionViewLayoutWidthHinting>) self.captionView setPreferredMaxLayoutWidth:self.bounds.size.width];
    }
}
```

I haven't investigated very deeply into this (other than getting this idea from [here](http://stackoverflow.com/a/13322872/670400)), since I've found a solution that works for my application, but I'd like to help improve this fantastic library, if possible.

Also, the solution proposed in https://github.com/NYTimes/NYTPhotoViewer/issues/55#issuecomment-103193882 didn't work in my specific use case. I needed to present the `NYTPhotosViewController`, then configure the UINavigationBar. I presume this is because it needs to be laid out at least once, and thus, the system hadn't applied the UIAppearance settings to the `UINavigationBar` instance.
