### ISSUE TITLE
Animated GIF support

### ISSUE THREAD

**Issue by kimar** [NYTimes/NYTPhotoViewer#69]
Are you planning to add animated GIF support?

**If not:** Would you potentially be interested in having this in? For us this is definitely a requirement and I'd be keen to implement this and create a PR.

Cheers,
Marcus

**Comment by cdzombak** [comment]
@kimar: we don't have plans to add animated GIF support in the near future, but we would welcome a PR adding such support.

If you'd like to propose a PR, there are two things we'd like to see in order to accept it…

- Please use https://github.com/Flipboard/FLAnimatedImage to add the support.
- If we can, let's make using it optional: let's allow enabling GIF support by building the library with a flag, but we don't want to make pulling in the code to support it mandatory.

**Comment by cdzombak** [comment]
_Closing this issue for now since this work isn't on our team's roadmap, but we'll welcome and review any PRs on this topic._
